34 weatherdata
BIM2SIM/bim2sim pull request #599
Opened 2023-10-27 09:27 UTC by DaJansenGit

2023-11-02 16:30 UTC, veronikarichter requested changes
Some minor modifications required, looks good in general.

2023-11-06 07:55 UTC, DaJansenGit commented on bim2sim/tasks/common/weather.py
> +            # weather_file = self.get_weatherfile_from_dwd(lat, long)
Only germany, I will do when/if we implement it.

2023-11-06 16:25 UTC, veronikarichter requested changes

2023-11-06 16:25 UTC, veronikarichter commented on test/unit/tasks/common/test_inspect.py
> +                test_rsrc_path / 'weather_files/DEU_NW_Aachen.105010_TMYx.epw')
```suggestion
                test_rsrc_path / 'weather_files/DEU_NW_Aachen.105010_TMYx.mos')
```

2023-11-06 16:25 UTC, veronikarichter commented on test/unit/tasks/common/test_inspect.py
> +                test_rsrc_path / 'weather_files/DEU_NW_Aachen.105010_TMYx.epw')
```suggestion
                test_rsrc_path / 'weather_files/DEU_NW_Aachen.105010_TMYx.mos')
```

2023-11-06 16:25 UTC, veronikarichter commented on test/unit/tasks/common/test_inspect.py
> +                test_rsrc_path / 'weather_files/DEU_NW_Aachen.105010_TMYx.epw')
```suggestion
                test_rsrc_path / 'weather_files/DEU_NW_Aachen.105010_TMYx.mos')
```

2023-11-06 16:28 UTC, veronikarichter approved these changes

2023-11-06 16:28 UTC, merged