Draft: 5 prepare plugincomfort for public repo
BIM2SIM/bim2sim pull request #655
Opened 2024-06-19 16:02 UTC by veronikarichter

2024-06-30 20:09 UTC, DaJansenGit requested changes
please address the mentioned points.

2024-06-30 20:09 UTC, DaJansenGit commented on bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/weather.py
obsolete file? please delete if yes.

2024-06-30 20:09 UTC, DaJansenGit commented on bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/ep_create_idf.py
Do the changes regarding fenestration have any impact on the existing EP generation? Because it seems like this will now always be processed and not only for comfort plugin.

2024-06-30 20:09 UTC, DaJansenGit commented on bim2sim/plugins/PluginComfort/test/integration/test_comfort.py
This seems like the same tests like for energyplus. I just checked one test in detail 'test_base_03_FZK_SB_design_day' but at least this one is the exact same as in PluginEnergyplus. Is there anything different? We should definitly reduce the number of tests to a minimum and don't run the same test twice.

2024-06-30 20:09 UTC, DaJansenGit commented on bim2sim/plugins/PluginComfort/bim2sim_comfort/utils/activity_clothing_ISO7730_ASHRAE_V001.json
put .json files under assets please

2024-06-30 20:09 UTC, DaJansenGit commented on bim2sim/plugins/PluginComfort/bim2sim_comfort/data/UseConditionsComfort_AC20-FZK-Haus.json
same here. If you need extra information for plugin comfort just add them to the existing use conditions. The current way produces a lot of redundant information.

2024-07-01 07:38 UTC, veronikarichter commented on bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/ep_create_idf.py
Fenestration was already implemented before, I just added an additional model cleanup for obsolete shading control elements, which caused errors during extensive testing of the plugin.

2024-07-01 07:38 UTC, veronikarichter commented on bim2sim/plugins/PluginEnergyPlus/bim2sim_energyplus/task/weather.py
removed.

2024-07-01 07:38 UTC, veronikarichter commented on bim2sim/plugins/PluginComfort/bim2sim_comfort/utils/activity_clothing_ISO7730_ASHRAE_V001.json
deleted this file (obsolete) and renamed /data to /assets.

2024-07-01 07:46 UTC, veronikarichter commented on bim2sim/plugins/PluginComfort/bim2sim_comfort/data/UseConditionsComfort_AC20-FZK-Haus.json
I created #674 to consider this issue in another branch

2024-07-01 11:43 UTC, DaJansenGit approved these changes
in the future we need to adress 
* [ ] use conditions #674 
as well as no duplicated tests @veronikarichter 

But for now we can merge this

2024-07-01 11:44 UTC, merged